export default Object.freeze({
  LISTING_DETAILS: "ListingDetails",
  LISTING_MAP_DETAILS: "ListingMapDetails",
  LISTING_DETAILS_AIRBNB: "ListingDetailsAirBnb",
  AUTHOR_LISTINGS: "AuthorListingsScreen",
  LISTING_EDIT: "ListingEdit",
  LOGIN: "Login",
  MESSAGES: "Messages",
  REGISTER: "Register",
  CATEGORY_SELECT: "Category",
  BLOG_DETAILS: "BlogDetail",
  BLOG_HOME: "BlogHomeScreen",
  BLOG_LISTINGS: "BlogListings",
  ALL_CARS_SCREEN: "AllListingsScreen",
  VIEW_MAP: "Map",
  HOUSE_ICON: "home-city-outline",
  CARS_ICON: "car-outline",
  JOBS_ICON: "account-search-outline",
  PLACES_ICON: "food-outline",
  EVENTS_ICON: "star-outline",
  ELECTRONICS_ICON: "cellphone-link",
  Coupons: "cellphone-link",

  HOUSE_MAP_ICON: "home",
  CARS_MAP_ICON: "car",
  JOBS_MAP_ICON: "account-search",
  PLACES_MAP_ICON: "food",
  EVENTS_MAP_ICON: "star",
  ELECTRONICS_MAP_ICON: "cellphone",
});
